name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Check licenses
        run: source .github/workflows/check_license.sh

      - name: Check Python scripts
        run: source .github/workflows/check_python_script.sh

      - name: Check Python formatting
        run: |
          pip install black
          black --check .

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Build package and run tests with Tox
        run: tox -e py
